import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { stdin, stdout } from "node:process";
import { createInterface, type Interface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import { Command } from "commander";

import { error, header, success } from "../utils/format.js";

async function prompt(rl: Interface, question: string, defaultValue: string): Promise<string> {
  const answer = await rl.question(`${question} [${defaultValue}]: `);
  return answer.trim() || defaultValue;
}

// Anvil's deterministic addresses after a fresh `scripts/dev.sh reset`. Users
// pointing at a remote deployment must edit the generated config.yaml by hand.
const ANVIL_CONTRACTS = {
  novelCore: "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
  roundManager: "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
  votingEngine: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
  prizePool: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
  bountyBoard: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
  rulesEngine: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
  userRegistry: "0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1",
} as const;

function renderConfig(rpcUrl: string, apiUrl: string): string {
  return `# Generated by \`onchain-novel-cli setup\`.
# Non-secret settings only. Secrets (PRIVATE_KEY, KEEPER_PRIVATE_KEY,
# VOTE_ENCRYPTION_KEY) belong in env vars, never here.
#
# When switching to a real deployment, update \`chain.rpcUrl\`, \`cli.apiUrl\`,
# and the \`contracts.*\` addresses. Other sections can stay as-is unless you
# also run backend/frontend yourself.

chain:
  rpcUrl: ${rpcUrl}
  chainId: 31337

# Anvil-deterministic addresses (what scripts/dev.sh reset produces locally).
# Replace with production addresses once deployed on-chain.
contracts:
  novelCore: "${ANVIL_CONTRACTS.novelCore}"
  roundManager: "${ANVIL_CONTRACTS.roundManager}"
  votingEngine: "${ANVIL_CONTRACTS.votingEngine}"
  prizePool: "${ANVIL_CONTRACTS.prizePool}"
  bountyBoard: "${ANVIL_CONTRACTS.bountyBoard}"
  rulesEngine: "${ANVIL_CONTRACTS.rulesEngine}"
  userRegistry: "${ANVIL_CONTRACTS.userRegistry}"

cli:
  apiUrl: ${apiUrl}
`;
}

export function registerSetupCommand(program: Command): void {
  program
    .command("setup")
    .description(
      "Interactively generate config.yaml in the current directory and drop " +
        "role-specific skill files into .claude/commands/ for Claude Code " +
        "(and similar agents).",
    )
    .action(async () => {
      try {
        header("Onchain Novel CLI Setup");

        // 1. Skill files ────────────────────────────────────────────────────
        const skillsDir = join(process.cwd(), ".claude", "commands");
        if (!existsSync(skillsDir)) {
          mkdirSync(skillsDir, { recursive: true });
        }

        // Resolve guides relative to this module file. Works in both layouts:
        //   dev tsc: dist/commands/setup.js → "../guides" → dist/guides
        //   prod tsup bundle: dist/onchain-novel-cli.js → "./guides" → dist/guides
        const here = dirname(fileURLToPath(import.meta.url));
        const guidesDir = existsSync(join(here, "guides"))
          ? join(here, "guides")
          : join(here, "..", "guides");
        const roles = ["author", "voter", "creator", "reader"] as const;
        for (const role of roles) {
          const guidePath = join(guidesDir, `${role}.md`);
          let content: string;
          try {
            content = readFileSync(guidePath, "utf-8");
          } catch {
            content = `# Novel ${role.charAt(0).toUpperCase() + role.slice(1)} Workflow\n\nRun \`onchain-novel-cli guide ${role}\` for details.\n`;
          }
          writeFileSync(join(skillsDir, `novel-${role}.md`), content);
        }
        success("Generated .claude/commands/novel-{author,voter,creator,reader}.md");

        // 2. config.yaml ────────────────────────────────────────────────────
        const configPath = join(process.cwd(), "config.yaml");
        if (existsSync(configPath)) {
          console.log(
            `\nconfig.yaml already exists at ${configPath} — keeping it. ` +
              "Delete it first if you want to regenerate.",
          );
        } else {
          const DEFAULT_RPC = "http://127.0.0.1:8545";
          const DEFAULT_API = "http://127.0.0.1:3001";
          let rpcUrl = DEFAULT_RPC;
          let apiUrl = DEFAULT_API;
          if (stdin.isTTY) {
            console.log(
              "\nI'll generate a config.yaml pre-filled for the local anvil stack.\n" +
                "Press Enter at each prompt to accept the default.\n",
            );
            const rl = createInterface({ input: stdin, output: stdout });
            try {
              rpcUrl = await prompt(rl, "Ethereum RPC URL", DEFAULT_RPC);
              apiUrl = await prompt(rl, "Backend API URL", DEFAULT_API);
            } finally {
              rl.close();
            }
          } else {
            console.log(
              "\nNon-interactive stdin — using defaults " +
                `(rpcUrl=${DEFAULT_RPC}, apiUrl=${DEFAULT_API}).`,
            );
          }
          writeFileSync(configPath, renderConfig(rpcUrl, apiUrl));
          success(`Wrote ${configPath}`);
        }

        console.log(
          "\nNext steps:\n" +
            "  - Edit config.yaml if your contract addresses differ from local anvil.\n" +
            "  - export PRIVATE_KEY=0x... before running write commands.\n",
        );
      } catch (err) {
        error(String(err));
        process.exit(1);
      }
    });
}
