import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { stdin, stdout } from "node:process";
import { createInterface, type Interface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import { Command } from "commander";

import { error, header, success } from "../utils/format.js";

async function prompt(rl: Interface, question: string, defaultValue: string): Promise<string> {
  const answer = await rl.question(`${question} [${defaultValue}]: `);
  return answer.trim() || defaultValue;
}

async function promptRequired(rl: Interface, question: string): Promise<string> {
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const answer = (await rl.question(`${question}: `)).trim();
    if (answer.length > 0) return answer;
    console.log("  (this field is required -- please provide a value)");
  }
}

const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;

function renderConfig(rpcUrl: string, apiUrl: string, novelCore: string): string {
  // chainId is intentionally absent -- services auto-detect via eth_chainId on
  // first connect. Pin it explicitly here only if you need offline tooling.
  // contracts.* beyond `novelCore` is also intentional: every other contract
  // is reachable from NovelCore's on-chain address book (resolveContracts).
  return `# Generated by \`onchain-novel-cli setup\`.
# Non-secret settings only. Secrets (PRIVATE_KEY, KEEPER_PRIVATE_KEY,
# VOTE_ENCRYPTION_KEY) belong in env vars, never here.
#
# When switching to a real deployment, update \`chain.rpcUrl\`, \`cli.apiUrl\`,
# and \`contracts.novelCore\`. The other contract addresses are derived
# on-chain from NovelCore at startup -- no manual upkeep needed.

chain:
  rpcUrl: ${rpcUrl}
  # chainId: 31337   # optional override; auto-detected from rpcUrl if omitted

contracts:
  novelCore: "${novelCore}"

cli:
  apiUrl: ${apiUrl}
`;
}

export function registerSetupCommand(program: Command): void {
  program
    .command("setup")
    .description(
      "Generate config.yaml plus a workflow skill for onchain-novel-cli. " +
        "Writes the skill to .agent/skills/onchain-novel/SKILL.md AND " +
        ".claude/commands/onchain-novel.md (so any agent can find it), and " +
        "drops onchain-novel-index.md at the project root as a discovery hint.",
    )
    .action(async () => {
      try {
        header("Onchain Novel CLI Setup");

        // 1. Skill files ────────────────────────────────────────────────────
        // The same SKILL.md is written to two well-known locations:
        //   .agent/skills/onchain-novel/SKILL.md  -- standard <skill>/SKILL.md
        //                                            convention (Cursor, Cline,
        //                                            Anthropic Skill API, etc.)
        //   .claude/commands/onchain-novel.md     -- Claude Code slash command
        //                                            (/onchain-novel)
        // Plus an index file at the project root for agents that don't
        // auto-scan either path.
        //
        // Resolve the bundled SKILL.md relative to this module file. Works
        // in both layouts:
        //   dev tsc:     dist/commands/setup.js -> "../guides/SKILL.md"
        //   tsup bundle: dist/onchain-novel-cli.js -> "./guides/SKILL.md"
        const here = dirname(fileURLToPath(import.meta.url));
        const guidesDir = existsSync(join(here, "guides"))
          ? join(here, "guides")
          : join(here, "..", "guides");
        const skillContent = readFileSync(join(guidesDir, "SKILL.md"), "utf-8");
        const indexContent = readFileSync(join(guidesDir, "onchain-novel-index.md"), "utf-8");

        const targets = [
          {
            dir: join(process.cwd(), ".agent", "skills", "onchain-novel"),
            file: "SKILL.md",
            content: skillContent,
            label: ".agent/skills/onchain-novel/SKILL.md",
          },
          {
            dir: join(process.cwd(), ".claude", "commands"),
            file: "onchain-novel.md",
            content: skillContent,
            label: ".claude/commands/onchain-novel.md",
          },
          {
            dir: process.cwd(),
            file: "onchain-novel-index.md",
            content: indexContent,
            label: "onchain-novel-index.md",
          },
        ];

        for (const t of targets) {
          if (!existsSync(t.dir)) mkdirSync(t.dir, { recursive: true });
          writeFileSync(join(t.dir, t.file), t.content);
          success(`Generated ${t.label}`);
        }

        // 2. config.yaml ────────────────────────────────────────────────────
        const configPath = join(process.cwd(), "config.yaml");
        if (existsSync(configPath)) {
          console.log(
            `\nconfig.yaml already exists at ${configPath} -- keeping it. ` +
              "Delete it first if you want to regenerate.",
          );
          return;
        }

        const DEFAULT_RPC = "http://127.0.0.1:8545";
        const DEFAULT_API = "http://127.0.0.1:3001";
        let rpcUrl = DEFAULT_RPC;
        let apiUrl = DEFAULT_API;
        let novelCore = "";

        if (stdin.isTTY) {
          console.log(
            "\nGenerating config.yaml. Press Enter to accept defaults where shown.\n" +
              "novelCore is the only contract address you need -- every other contract\n" +
              "is discovered on-chain from there at startup.\n",
          );
          const rl = createInterface({ input: stdin, output: stdout });
          try {
            rpcUrl = await prompt(rl, "Ethereum RPC URL", DEFAULT_RPC);
            apiUrl = await prompt(rl, "Backend API URL", DEFAULT_API);
            // eslint-disable-next-line no-constant-condition
            while (true) {
              novelCore = await promptRequired(rl, "NovelCore proxy address (0x...)");
              if (ADDRESS_RE.test(novelCore)) break;
              console.log("  not a 0x-prefixed 20-byte hex address -- try again");
            }
          } finally {
            rl.close();
          }
        } else {
          console.log(
            "\nNon-interactive stdin -- writing a placeholder config.yaml " +
              `(rpcUrl=${DEFAULT_RPC}, apiUrl=${DEFAULT_API}, novelCore=<unset>).\n` +
              "Edit contracts.novelCore by hand before running any chain command.",
          );
        }

        writeFileSync(configPath, renderConfig(rpcUrl, apiUrl, novelCore));
        success(`Wrote ${configPath}`);

        console.log(
          "\nNext steps:\n" +
            "  - Edit config.yaml if anything's wrong.\n" +
            "  - export PRIVATE_KEY=0x... before running write commands.\n",
        );
      } catch (err) {
        error(String(err));
        process.exit(1);
      }
    });
}
